# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{geocoder_plus}
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Fajar A B"]
  s.date = %q{2011-04-13}
  s.description = %q{This gem consists two additional geocoders for geokit, Yahoo! PlaceFinder and Google V3}
  s.email = %q{fajar.ab@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README",
    "README.rdoc"
  ]
  s.files = [
    "lib/geocoder.rb",
    "lib/geocoder_plus.rb",
    "lib/geocoders/google_v3_geocoder.rb",
    "lib/geocoders/yahoo_place_finder_geocoder.rb"
  ]
  s.homepage = %q{http://github.com/fajarb/geocoder_plus}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.1}
  s.summary = %q{Additional geocoders for geokit gem}
  s.test_files = [
    "test/helper.rb",
    "test/test_geocoder_plus.rb",
    "test/test_google_v3_geocoder.rb",
    "test/test_yahoo_place_finder_geocoder.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<geokit>, [">= 1.5.0"])
      s.add_runtime_dependency(%q<yajl-ruby>, [">= 0.8.2"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<mocha>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<geokit>, [">= 1.5.0"])
      s.add_dependency(%q<yajl-ruby>, [">= 0.8.2"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<mocha>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<geokit>, [">= 1.5.0"])
    s.add_dependency(%q<yajl-ruby>, [">= 0.8.2"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<mocha>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

